-- Run command: db2 -tvf create_function.sh

CONNECT TO TESTDB;

CREATE OR REPLACE FUNCTION IRIS_PP_UDF(FLOAT, FLOAT, FLOAT, FLOAT)
  RETURNS CHAR(10)
  LANGUAGE PYTHON
  PARAMETER STYLE NPSGENERIC
  FENCED
  NOT THREADSAFE
  ALLOW PARALLEL
  NO DBINFO
  NOT DETERMINISTIC
  NO EXTERNAL ACTION
  RETURNS NULL ON NULL INPUT
  NO SQL
  EXTERNAL NAME '/home/db2inst1/h2o_driverless_ai/Db2_UDF_with_H2O_DAI_Python_Pipeline/iris_predict_pp_udf.py';

CONNECT RESET;
