-- Run command: db2 -tvf create_function.sh

CONNECT TO TESTDB;

CREATE OR REPLACE FUNCTION SCORE_WITH_REST_API(FLOAT, FLOAT, FLOAT, FLOAT)
  RETURNS CHAR(10)
  LANGUAGE PYTHON
  PARAMETER STYLE NPSGENERIC
  FENCED
  --NOT THREADSAFE
  --NO FINAL CALL
  ALLOW PARALLEL
  --NO DBINFO
  --DETERMINISTIC
  NO EXTERNAL ACTION
  RETURNS NULL ON NULL INPUT
  NO SQL
  EXTERNAL NAME '/home/db2inst1/h2o_driverless_ai/Db2_UDF_to_DAI_REST/score_with_rest_api.py';

CONNECT RESET;
