-- Run command: db2 -tvf create_function.sh

CONNECT TO TESTDB;

CREATE OR REPLACE FUNCTION SCORE_WITH_REST_API(FLOAT, FLOAT, FLOAT, FLOAT)
  RETURNS CHAR(10)
  LANGUAGE PYTHON
  PARAMETER STYLE NPSGENERIC
  FENCED
  ALLOW PARALLEL
  NO EXTERNAL ACTION
  RETURNS NULL ON NULL INPUT
  NO SQL
  EXTERNAL NAME '/home/db2inst1/h2o_driverless_ai/Db2_UDF_to_H2O_DAI_HTTP_Scoring_Service/score_with_rest_api.py';

CONNECT RESET;
